# Generated by Django 5.0.4 on 2024-05-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='clothes_type',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('pants', 'Pants'), ('suits', 'Suits'), ('dresses', 'Dresses'), ('others', 'Others')], default='others', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
