# Generated by Django 5.0.4 on 2024-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0004_product_category_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='laundry_items',
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_address',
            field=models.TextField(default='Default Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_id',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='full_name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default='Default Payment', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(default='Default Number', max_length=15),
            preserve_default=False,
        ),
    ]
