# Generated by Django 5.0.4 on 2024-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0005_remove_transaction_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(default='Default Not Specified', max_length=20),
            preserve_default=False,
        ),
    ]
