# Generated by Django 5.0.4 on 2024-05-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0006_checkout_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
