# Generated by Django 5.0.4 on 2024-05-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0007_checkout_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='is_paid',
        ),
    ]
