# Generated by Django 5.0.4 on 2024-05-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0008_remove_checkout_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactionproduct',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactionproduct',
            name='product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='clothes_type',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('pants', 'Pants'), ('suits', 'Suits'), ('skirts', 'Skirts'), ('dresses', 'Dresses'), ('others', 'Others')], default='others', max_length=50),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionProduct',
        ),
    ]
