# Generated by Django 5.0.4 on 2024-05-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0010_remove_cart_clothes_amount_remove_cart_clothes_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
