# Generated by Django 5.0.4 on 2024-08-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0012_cart_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('delivery_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], default='Pending', max_length=10)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laundry.cart')),
            ],
        ),
    ]
