# Generated by Django 5.0.4 on 2024-08-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0014_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
