# Generated by Django 5.0.4 on 2024-08-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0015_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='delivery_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('mobile_money', 'Mobile Money'), ('wallet', 'Wallet')], default='credit_card', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
