# Generated by Django 5.0.4 on 2024-08-23 23:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0018_alter_checkout_cart_alter_servicecart_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='status',
        ),
        migrations.AddField(
            model_name='checkout',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.cart'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='delivery_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email_id',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
